/**
 * Package grouping the custom exceptions generated by the model entities
 */
@ParametersAreNonnullByDefault
package it.polimi.ingsw.server.model.exceptions;

import javax.annotation.ParametersAreNonnullByDefault;